apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Enables application status badge feature
  statusbadge.enabled: "true"
  url: https://172.17.8.111:8888
  dex.config: |
    connectors:
      - type: ldap
        id: ldap
        name: LDAP
        config:
          host: 172.17.8.111:389
          insecureNoSSL: true
          bindDN: cn=admin,dc=scytalelabs,dc=com
          bindPW: adminPassword
          startTLS: false
          userSearch:
            baseDN: dc=scytalelabs,dc=com
            filter: "(objectClass=posixAccount)"
            username: uid
            idAttr: uid
            emailAttr: mail
            nameAttr: uid
          groupSearch:
            baseDN: cn=group,dc=scytalelabs,dc=com
            filter: "(objectClass=posixGroup)"
            userMatchers:
            - userAttr: uid
              groupAttr: memberUid
            nameAttr: cn
  repositories: |
    - url: https://github.com/hwchiu/hiskio-gitops-argocd-manifest.git
    - url: https://github.com/hwchiu/hiskio-gitops-demo-manifest.git
