apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    p, role:gitops-ro, applications, get, */*, allow
    p, role:gitops-ro, repositories, get, *, allow
    p, role:gitops-ro, repositories, create, *, allow
    p, role:gitops-ro, repositories, update, *, allow
    p, role:gitops-ro, repositories, delete, *, allow

    g, read, role:gitops-ro
  policy.default: role:gitops-ro
